controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diagnostics:
      threshold:
        controllers:
          execution_time:  # refers to controller's update cycle execution time in us
            mean_error:
              warn: 150.0
              error: 500.0
            standard_deviation:
              warn: 50.0
              error: 150.0

    # position_proportional_gain: 0.5

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    is_async: true
    update_rate: 100
