controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    thread_priority: 98  # Range: 0-99. Default is 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diagnostics:
      threshold:
        controllers:
          execution_time:  # refers to controller's update cycle execution time in us
            mean_error:
              warn: 1000.0
              error: 2000.0
            standard_deviation:
              warn: 100.0
              error: 200.0

ur5_effort_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    interface_name: effort
